Cnn wet dry
pycomlink/pycomlink pull request #67
Opened 2020-10-09 12:16 UTC by jpolz

Add a wet/dry function using the cnn method.

- [ ] Add trained cnn files to subdirectory of wet/dry

- [ ] Add function for (txrx_ch_1,txrx_ch_2)-->wet/dry

- [ ] Add test for wet dry classification

Reference: https://doi.org/10.5194/amt-13-3835-2020

2020-10-13 16:09 UTC, jpolz commented
Test is done, but not perfect. Problem is that a new version of the cnn would change the results, therefore I just check if the output length of the array is fine.

2020-10-13 19:03 UTC, cchwala requested changes

2020-10-13 19:03 UTC, cchwala commented on pycomlink/processing/wet_dry/cnn.py
> +def get_test_data_path():
should use a meaningful name

2020-10-13 19:03 UTC, cchwala commented on pycomlink/processing/wet_dry/cnn.py
> +    df = df.dropna()
not sure, but doesn't this just fill in -9999 at the locations of the NaNs. If yes, then this is a bit confusing

2020-10-13 19:03 UTC, cchwala commented on pycomlink/processing/wet_dry/cnn.py
> +        0,
maybe add the keyword here and in the next line, then it is more readable

2020-10-13 19:03 UTC, cchwala commented on pycomlink/processing/wet_dry/cnn.py
> +            -9999 in df["trsl1"].values[i - 151 : i + 31]
can you add a comment on what this does and why?

2020-10-13 19:03 UTC, cchwala commented on pycomlink/processing/wet_dry/cnn.py
> +    return df.prediction.values > threshold
Not sure if this complicates things much, but it might be good to also have the option to return the prediction values, e.g. to plot them as time series in comparison to e.g. the time series of the rolling std_dev.

Maybe this could be done by havin a speparate return for the case `threshold=None`.

2020-10-13 19:03 UTC, cchwala commented on pycomlink/processing/wet_dry/cnn.py
> +    json_file = open(modeljson_fn, "r")
How long does this part with the model init take in comparison to the rest of the code when used with e.g. one week data from one CML?

If it takes "too long", the initialization could also be done outside of the function at import time.

2020-10-13 19:05 UTC, cchwala commented
> Test is done, but not perfect. Problem is that a new version of the cnn would change the results, therefore I just check if the output length of the array is fine.

This does not seem to be very robust against unexpected changes. If a new version of the CNN gets added, then the test has to be adapted, or tests for individual "versions" of the CNN might be an option.

2020-10-13 19:27 UTC, jpolz commented on pycomlink/processing/wet_dry/cnn.py
> +    df = df.dropna()
NaNs can not be handled by the CNN, therefore they are replaced by -9999. afterwards -9999 will again lead to a NaN in the prediction. It is not trivial to do predictions just for the samples containing no NaNs.

2020-10-13 19:31 UTC, jpolz commented on pycomlink/processing/wet_dry/cnn.py
> +    return df.prediction.values > threshold
Should be easy! But it has to be more obvious to not cause troubles later when the function is used blindly with other functions. Maybe `return_raw_predictions=True`

2020-10-13 19:49 UTC, jpolz commented on pycomlink/processing/wet_dry/cnn.py
> +    json_file = open(modeljson_fn, "r")
it makes sense to do this anyways since the model data is small.

2020-10-13 20:00 UTC, jpolz commented
> > Test is done, but not perfect. Problem is that a new version of the cnn would change the results, therefore I just check if the output length of the array is fine.
> 
> This does not seem to be very robust against unexpected changes. If a new version of the CNN gets added, then the test has to be adapted, or tests for individual "versions" of the CNN might be an option.

What could be a meaningful test then? It is also risky to update the exact expected output for every new model version that we implement.

2020-10-13 20:01 UTC, jpolz commented on pycomlink/processing/wet_dry/cnn.py
> +    json_file = open(modeljson_fn, "r")
650 kB in total. I move it to outside the function.

2020-10-13 20:06 UTC, jpolz commented on pycomlink/processing/wet_dry/cnn.py
> +            -9999 in df["trsl1"].values[i - 151 : i + 31]
Done.

2020-10-14 04:50 UTC, jpolz commented
> I would test using a given example trsl time series and a "known" expected result which you have to get from running your code and checking yourself if the result makes sense. There is no way (that I know of...) to write a generic test for this sort of data processing functions. The correctness, and this is what tests are about, can only be checked by applying it to an example dataset.
> 
> The problem is that e.g. updates to your imported dependencies might change your results. You want to make sure that this is caught by a test. For a new model, you will have to update the test. Yes. But I do not see any problem with this. You commit some code for the new model, anyway, so you can also update the test then.

This should be resolved now. Although I do not test on a real TRSL time series the test should test if the model always performs the exact same numerical operations.

2020-10-14 08:40 UTC, jpolz commented on pycomlink/processing/wet_dry/cnn.py
> +    df = df.dropna()
I replaced this routine by `df.fillna()`

2020-10-14 09:47 UTC, cchwala commented
Tests do not run because your new dependencies are not in https://github.com/pycomlink/pycomlink/blob/v0.3alpha/.travis.yml
Just add them there, or even better, parser the dependencies from `requirements.txt`.

2020-10-14 10:10 UTC, jpolz commented
Done

2020-10-15 19:55 UTC, cchwala approved these changes

2020-10-15 19:55 UTC, cchwala commented
Looks good!

CNN wet-dry classification in pycomlink! 🚀

2020-10-15 19:57 UTC, merged